# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
development:
  adapter: mysql2 # install mysql2 to gem
  encoding: utf8
  reconnect: false
  database: Parks #database name
  pool: 5
  username: <user name>
  password: <your password>
  host: localhost
